language: node_js
node_js:
- 0.10
- 0.8
- 0.6

services:
- mongodb

before_script:
- npm install
- bower install

script: npm test

notifications:
email:
- "swarthant1240@gmail.com"
- "john@gmail.com"
